### ISSUE TITLE
Error writing to database

### ISSUE THREAD

**Issue by mrvinceo** [caiocarvalhofre/mod_maici#1]
Many thanks for working on this plugin - I see a lot of potential value in this, but I'm getting an error when attempting to save the activity's settings within the course context.  Error provided below. All options were set, and the fields which aren't specific to the plugin (Description, Title etc.) are saved to the database. It seems to relate to the prompt-length, as setting this to just a few words appears to resolve the issue, but limits how much instruction can then be fed to the model.

We're on Moodle 4.1 in the environmant being tested.

> Debug info: Data too long for column 'prompt' at row 1
> UPDATE mdl_maici SET name = ?,apikey = ?,assistantname = ?,username = ?,maxperday = ?,maxperuser = ?,maxpermonth = ?,apitype = ?,model = ?,prompt = ?,sourceoftruth = ?,assistant = ?,assistantfile = ?,completionaiexchanges = ?,course = ?,instructionsformat = ?,instructions_submit = ?,completionai = ?,intro = ?,introformat = ?,timemodified = ? WHERE id=?
> -- line 1636 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->update_record_raw()
> -- line 160 of /mod/maici/lib.php: call to mysqli_native_moodle_database->update_record()
> -- line 647 of /course/modlib.php: call to maici_update_instance()
> -- line 168 of /course/modedit.php: call to update_moduleinfo()
> [array (
> 0 => 'A chat about The Old Man and the Sea',
> 1 => 'sk-xxxxxxxxxxxxxxxxxxxxxxxx',
> 2 => 'Assistant',
> 3 => 'User',
> 4 => 3000,
> 5 => 3000,
> 6 => 3000,
> 7 => 'chat',
> 8 => 'gpt-4',
> 9 => 'This is a discussion about Hemingway\'s Novella \'The Old Man and the Sea\'. The student (user) has been asked to outline the main themes of this text, you will respond to as an experienced teacher of literature would. You will address any statements made by the student which you believe to be incorrect or invalid, and will highlight aspects which are well considered and worth exploring further. You are a critical assistant, who is encouraging and kind, and would never cause any offence even if provoked. ',
> 10 => '',
> 11 => 'asst_bg6oQmZeygroYwVsuBiyErlB',
> 12 => 48014220,
> 13 => '1',
> 14 => '331',
> 15 => '1',
> 16 => '<p dir="ltr" style="text-align: left;">This is a discussion about Hemingway\'s Novella \'The Old Man and the Sea\'. Please respond with your thoughts on what the main themes are within this novella.</p>',
> 17 => 0,
> 18 => '<p dir="ltr" style="text-align: left;">This is a discussion about Hemingway\'s Novella \'The Old Man and the Sea\'.&nbsp;</p>',
> 19 => '1',
> 20 => 1708341362,
> 21 => '1',
> )]
> Error code: dmlwriteexception

**Comment by taymossimc** [comment]
Thanks for finding this bug. We are looking into it.

**Comment by taymossimc** [comment]
@mrvinceo Try the latest release.... this bug should be fixed, now 
https://github.com/caiocarvalhofre/mod_maici/releases/tag/MAICI-v.1.1-beta

**Comment by MURBASLMS** [comment]
Hi, on 4.1, latest main commit, I'm still getting this:

Debug info: ERROR: null value in column "assistant" of relation "mdl_maici" violates not-null constraint
DETAIL: Failing row contains (5, 23896, ICT101 assistant, , 1, , 1, APIKEY, chat, User, ICT101, null, 1, gpt-4o, 0, 0, 0, , , 0, 0, , 0, 0, 1, 1722647300, 0).
INSERT INTO mdl_maici (name,apikey,assistantname,username,maxperday,maxperuser,maxpermonth,apitype,model,prompt,sourceoftruth,completionaiexchanges,course,instructionsformat,instructions_submit,completionai,assistant,intro,introformat,timecreated,instructiontokens) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) RETURNING id
[array (
'name' => 'ICT101 assistant',
'apikey' =>
'assistantname' => 'ICT101',
'username' => 'User',
'maxperday' => 0,
'maxperuser' => 0,
'maxpermonth' => 0,
'apitype' => 'chat',
'model' => 'gpt-4o',
'prompt' => '',
'sourceoftruth' => '',
'completionaiexchanges' => 1,
'course' => '23896',
'instructionsformat' => '1',
'instructions_submit' => '',
'completionai' => 0,
'assistant' => NULL,
'intro' => '',
'introformat' => '1',
'timecreated' => 1722647300,
'instructiontokens' => 0,
)]
Error code: dmlwriteexception
