### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by levi19982** [caiocarvalhofre/mod_maici#2]
I see a lot of potential in this, I hope you continue to develop this plugin.

**Comment by taymossimc** [comment]
Thanks. That is, indeed, our plan!  Have you loaded it onto a Moodle Site and tried it, yet?

**Comment by levi19982** [comment]
Yes I already tried it, worked fine both with Assistant API or custom prompt in settings, I just dont understand one thing, I set the:
Tokens per day, Tokens per user and Tokens per month to 3000 and still got this error: "We are sorry, but you have reached the limit of your available interactions—please try again tomorrow." after x number of exchange, why? What is "available interaction"? Sorry for the question. And one more thing, do you plan on adding more completion criteria? Like we can tell the GPT when to set it to completed and it's the GPT who decides if the user completed the activity, or this is something that cannot be achieved?

**Comment by taymossimc** [comment]
How long was your initializing prompt?

**Comment by levi19982** [comment]
2 sentences, about 15 words this is why I do not understand

**Comment by caiocarvalhofre** [comment]
Please check your token usage in "MAICI report". There you can check how many token was used for each exchange.

**Comment by caiocarvalhofre** [comment]
Hi @levi19982 we added more token transparency. You can also set max token limits to 0 (unlimited token usage)
