### ISSUE TITLE
404 error for requests to /mod/maici/api/completion.php

### ISSUE THREAD

**Issue by pidaback** [caiocarvalhofre/mod_maici#3]
I have installed the main branch both locally and on a test server. Installation and creating an activity in moodle went flawlessly.

However, when I try to send a message, _completion.php_ is not found. The server responds with 404 to requests sent to http://localhost:8080/mod/maici/api/completion.php (on my development machine using Docker) or https://example.com/mod/maici/api/completion.php (where example.com stands for my test server). This is about the request in the *createCompletion()* function in the JavaScript file.

When I copy the request as cURL from Chrome DevTools and send it via Terminal or Postman, I get a response.

We are very excited about the development of this plug-in. The possibility to work with different system prompts within a moodle instance and to set limits per user or time period - this is exactly what we are currently looking for!

**Comment by taymossimc** [comment]
@pidaback Thanks for the note - we are taking a look at this bug.

**Comment by caiocarvalhofre** [comment]
Hi @pidaback, can you please provide more info about your plugin instance settings, are you using chat or assistant, etc. Thank you for your feedback.

**Comment by pidaback** [comment]
Thank you so much for looking into this so quickly!

It depends on the language model:
- The chat type does not work with the GPT 4 models. It works with the GPT 3.5 models.
- For the assistant type, the model is determined by a setting in our OpenAI account. I can only use 3.5 models until I add more money to our account. Currently, the assistant is working.

Apparently $10 or $15 [need to be available](https://community.openai.com/t/no-access-to-new-gpt-4-turbo-as-a-model-in-assistant-builder-model-dropdown/477570) to use assistants with GPT-4. Possibly such a restriction also applies to the chat type.

I will get back to you on this soon. For now, I think the only problem here is a misleading error message.

**Comment by taymossimc** [comment]
Yeah, I just tested it and it works fine with ChatGPT 4 in both the regular chat and in with the Assistants. So I think this is just an issue with what the account will allow.  

But you said you got a werid 404 error? Can you explain the circumstances that created it? Not enough money in the account and you had chosen GPT4 as the model?  Is that right?

**Comment by taymossimc** [comment]
Hmm. Okay, we'll take a look and see if wte can get a better handling of this error condition.  thanks!

**Comment by caiocarvalhofre** [comment]
Hi @pidaback please check latest changes. We added additional response error info directly in chat.

**Comment by pidaback** [comment]
Thank you! Since our account on openai.com is charged now, I can't check if your commit fixes the bug I originally reported.

However, I was able to create a similar situation by setting up a MAICI activity with an assistant that I later removed from our OpenAI account.

With both the old and new versions of your plugin, I get error 404 for requests to _completion.php_ and "Error..." appears in the text input. I have to open DevTools to get information about the cause of the error: The response for the request to _completion.php_ contains "No assistant found with id 'id>'". Your new code does not catch this because in this case, _$response_ is never created in _completion.php_.

I don't think this problem will occur often, but I wanted to let you know that your approach will not catch all errors where a request to _completion.php_ fails.
