### ISSUE TITLE
Assistant API type broken because property_exists() does not work with arrays

### ISSUE THREAD

**Issue by pidaback** [caiocarvalhofre/mod_maici#4]
One of your [latest commits](https://github.com/caiocarvalhofre/mod_maici/commit/f3a56cd2c9fc5de69f5bd974797e847da2f58a76) adds a condition to _completion.php_ (line 76): `if(property_exists($response,'error'))`

_property_exists()_ works for objects only, but I think that for assistants, your code always returns an array (see the _create_completion()_ methods in _completion/assistant.php_ and _completion/chat.php_, respectively).

With the assistant API type, I get error 404 for requests to _completion.php_, very similar to [another issue](https://github.com/caiocarvalhofre/mod_maici/issues/3) I reported a few weeks ago. In this case, the actual problem is _Argument #1 ($object_or_class) must be of type object|string, array given_ caused by the condition I mentioned.

**Comment by caiocarvalhofre** [comment]
Hi @pidaback. You missed that. It should be fixed now also for assistant. Now when there is an error in response it returns object.
